### ISSUE TITLE
Can't use tokenizer.fit_tranform

### ISSUE THREAD

**Issue by Zylinks** [rkcosmos/deepcut#40]
i copy example and paste it into VSCode but Error

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    X = tokenizer.fit_tranform(['ฉันบินได้', 'ฉันกินข้าว', 'ฉันอยากบิน']) # 3 x 4 CSR sparse matrix
  File "/home/winnie/anaconda3/envs/tensorflow/lib/python3.5/site-packages/deepcut/deepcut.py", line 278, in fit_tranform
    X = self.transform(raw_documents, new_document=True)
  File "/home/winnie/anaconda3/envs/tensorflow/lib/python3.5/site-packages/deepcut/deepcut.py", line 267, in transform
    self.max_features)
  File "/home/winnie/anaconda3/envs/tensorflow/lib/python3.5/site-packages/deepcut/deepcut.py", line 214, in _limit_features
    if not kept_indices:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

![screenshot from 2018-09-10 00-08-38](https://user-images.githubusercontent.com/31320324/45281969-69e87d80-b48e-11e8-8708-fff0fa5ee2e0.png)
![screenshot from 2018-09-10 00-10-59](https://user-images.githubusercontent.com/31320324/45282000-84baf200-b48e-11e8-8d87-cc11c420e559.png)

**Comment by titipata** [comment]
Hi @Zylinks, you probably have the older version of `deepcut`. You can install `deepcut` from master branch by using `pip install git+git://github.com/rkcosmos/deepcut.git`. This should solve the issue here.

The recent `deepcut` uses `if len(kept_indices) == 0:` instead of `if not kept_indices` (see [here](https://github.com/rkcosmos/deepcut/blob/master/deepcut/deepcut.py#L214)).

**Comment by Zylinks** [comment]
Thx so much
